// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srqmyddwgtmoachwnlfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNycW15ZGR3Z3Rtb2FjaHdubGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1Nzk3NjksImV4cCI6MjA2MTE1NTc2OX0.hvKUXxNMZUy4yYPwof-AiU8XeBMV4XRblwNjiTTuBT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);